/**
 * Wiki scaffolding: ensure the wiki directory has DEVNEURAL.md, index.md,
 * log.md, and the standard subdirectories on first daemon launch.
 *
 * The schema doc DEVNEURAL.md is copied from docs/spec/DEVNEURAL.md in
 * the repo. If that source is absent (deployed without docs), a minimal
 * fallback is written. Runtime edits to the wiki copy are preserved
 * unless the spec source is newer.
 */
import * as fs from 'node:fs';
import * as path from 'node:path';
import { execSync } from 'node:child_process';
import {
  wikiRoot,
  wikiPagesDir,
  wikiPendingDir,
  wikiArchiveDir,
  wikiSchemaFile,
  wikiIndexFile,
  wikiLogFile,
  wikiWhatsNewFile,
  ensureDir,
} from '../paths.js';

function specSourcePath(): string {
  // 07-daemon/dist/wiki/scaffolding.js -> .../07-daemon/dist/wiki/scaffolding.js
  // candidate spec: c:/dev/Projects/DevNeural/docs/spec/DEVNEURAL.md
  return 'C:/dev/Projects/DevNeural/docs/spec/DEVNEURAL.md';
}

const FALLBACK_SCHEMA = `# DEVNEURAL.md

> Fallback schema document. The canonical version lives at
> docs/spec/DEVNEURAL.md in the DevNeural repo. Replace this file
> with the up-to-date schema before relying on automated ingest.

Pages must follow the [trigger] -> [insight] format. See the repo for
full standing instructions.
`;

const INDEX_HEADER = `# Wiki index

This file is regenerated by the daemon. Each row links to a page in
\`pages/\`, \`pending/\`, or \`archive/\`.

Last regenerated: never.
`;

const LOG_HEADER = `# Wiki log

Append-only audit trail. One line per ingest, lint, reconcile, or
prune action.
`;

const WHATS_NEW_HEADER = `# What's new

The lint pass writes a weekly digest here.
`;

export interface ScaffoldResult {
  created: string[];
  updated: string[];
  alreadyPresent: string[];
}

export function ensureWiki(): ScaffoldResult {
  const created: string[] = [];
  const updated: string[] = [];
  const alreadyPresent: string[] = [];

  const dirs = [
    wikiRoot(),
    wikiPagesDir(),
    wikiPendingDir(),
    wikiArchiveDir(),
  ];
  for (const d of dirs) {
    if (!fs.existsSync(d)) {
      ensureDir(d);
      created.push(d);
    } else {
      alreadyPresent.push(d);
    }
  }

  // Schema doc: copy from spec if newer or missing
  const schemaTarget = wikiSchemaFile();
  const schemaSource = specSourcePath();
  if (fs.existsSync(schemaSource)) {
    const targetExists = fs.existsSync(schemaTarget);
    const sourceMtime = fs.statSync(schemaSource).mtimeMs;
    const targetMtime = targetExists ? fs.statSync(schemaTarget).mtimeMs : 0;
    if (!targetExists) {
      fs.copyFileSync(schemaSource, schemaTarget);
      created.push(schemaTarget);
    } else if (sourceMtime > targetMtime) {
      fs.copyFileSync(schemaSource, schemaTarget);
      updated.push(schemaTarget);
    } else {
      alreadyPresent.push(schemaTarget);
    }
  } else if (!fs.existsSync(schemaTarget)) {
    fs.writeFileSync(schemaTarget, FALLBACK_SCHEMA, 'utf-8');
    created.push(schemaTarget);
  } else {
    alreadyPresent.push(schemaTarget);
  }

  if (!fs.existsSync(wikiIndexFile())) {
    fs.writeFileSync(wikiIndexFile(), INDEX_HEADER, 'utf-8');
    created.push(wikiIndexFile());
  } else {
    alreadyPresent.push(wikiIndexFile());
  }
  if (!fs.existsSync(wikiLogFile())) {
    fs.writeFileSync(wikiLogFile(), LOG_HEADER, 'utf-8');
    created.push(wikiLogFile());
  } else {
    alreadyPresent.push(wikiLogFile());
  }
  if (!fs.existsSync(wikiWhatsNewFile())) {
    fs.writeFileSync(wikiWhatsNewFile(), WHATS_NEW_HEADER, 'utf-8');
    created.push(wikiWhatsNewFile());
  } else {
    alreadyPresent.push(wikiWhatsNewFile());
  }

  // Initialize git repo if not present
  initWikiGit();

  return { created, updated, alreadyPresent };
}

function initWikiGit(): void {
  const gitDir = path.posix.join(wikiRoot(), '.git');
  if (fs.existsSync(gitDir)) return;
  try {
    execSync('git init -q', { cwd: wikiRoot(), stdio: 'ignore', windowsHide: true });
    execSync('git -c "user.email=devneural@local" -c "user.name=DevNeural" add .', {
      cwd: wikiRoot(),
      stdio: 'ignore',
      windowsHide: true,
    });
    execSync(
      'git -c "user.email=devneural@local" -c "user.name=DevNeural" commit -q -m "wiki: initial scaffold"',
      { cwd: wikiRoot(), stdio: 'ignore', windowsHide: true },
    );
  } catch {
    /* git not available or init failed; non-fatal */
  }
}

export function appendLog(line: string): void {
  const stamp = new Date().toISOString();
  fs.appendFileSync(wikiLogFile(), `- ${stamp} ${line}\n`, 'utf-8');
}

export function commitWiki(message: string): void {
  try {
    execSync(
      `git -c "user.email=devneural@local" -c "user.name=DevNeural" add -A && git -c "user.email=devneural@local" -c "user.name=DevNeural" commit -q --allow-empty -m "${message.replace(/"/g, '\\"')}"`,
      { cwd: wikiRoot(), stdio: 'ignore', shell: 'bash', windowsHide: true },
    );
  } catch {
    /* ignore git failures; wiki is the source of truth on disk */
  }
}
